### ISSUE TITLE
SSL/TLS Certs for ltdp.org expired

### ISSUE THREAD

**Issue by webghostdeveloper** [tLDP/LDP#115]
Sorry to post this here but namecheap wants me to create and account just to let you know the ssl certs are expired. Maybe consider changing to letsencrypt/certbot!? -thanks

**Comment by ser** [comment]
thanks, fixed, server hasn't restarted itself after cert replacement :(

**Comment by webghostdeveloper** [comment]
thank you, your work is much appreciated
