### ISSUE TITLE
Where is “The Linux Programmer’s Guide”?

### ISSUE THREAD

**Issue by Zearin** [tLDP/LDP#4]
I’m trying to find the source for “The Linux Programmer’s Guide”, as seen online at http://www.tldp.org/LDP/lpg/lpg.html.

I’ve looked around, but this project is huge, and I’m having trouble finding it.  

(Does it even live here?  The “About” of the above-linked document says it’s written in TeX…)

**Comment by apjanke** [comment]
I don't think it's in this repo.

The Guides are listed on their own page on the LDP website, with the LPG at http://www.tldp.org/guides.html#lpg, which is inside the "Older / Unmaintained" section. I don't see any of the "Unmaintained" guides in this repo.

If you just want a snapshot of the TeX source of the last version, go to the LPG distribution at http://www.tldp.org/pub/Linux/docs/ldp-archived/programmers-guide/ and download `lpg-0.4.tar.gz`. That contains the TeX source files.

**Comment by martin-a-brown** [comment]
Long since handled (thank you, apjanke).  I've added a note to call out the original sources of the Linux Programmer's Guide.
