### ISSUE TITLE
Broken link on http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-14.html

### ISSUE THREAD

**Issue by tjaensch** [tLDP/LDP#57]
This link http://org.laol.net/lamug/beforever/bashtut.htm at the bottom of http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-14.html is broken.

**Comment by martin-a-brown** [comment]
Greetings Thomas,

I have added a link in the Bash-Prog-Intro-HOWTO near the dead link to the last known snapshot of that content from the Wayback Machine.

Thank you for your earlier pull requests and this observation.

-Martin
