### ISSUE TITLE
linuxdoc.org unreachable

### ISSUE THREAD

**Issue by AliMD** [tLDP/LDP#87]
Domain linuxdoc.org is unreachable and all links not works anymore
But `linuxdocs.org` is available! is this domain related to `tLDP` officially?
May I make a PR and changes all links to main `tldp.org` or `linuxdocs.org`?

**Comment by pbiering** [comment]
hmm, looks like linuxdoc.org got a permanent redirect:

```
curl -v http://linuxdoc.org
*   Trying 184.168.131.241:80...
* TCP_NODELAY set
* Connected to linuxdoc.org (184.168.131.241) port 80 (#0)
> GET / HTTP/1.1
> Host: linuxdoc.org
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.12.2
< Date: Mon, 29 Jul 2019 06:28:08 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: close
< Location: http://www.acumenprep.com/
< 
* Closing connection 0
```

final destination can't be resolved currrenty...this is very strange

**Comment by ser** [comment]
linuxdoc.org was stolen by previous LDP rogue admin, all links to it should be removed.

**Comment by AliMD** [comment]
Can I make PR for this?

**Comment by ser** [comment]
For replacing linuxdoc.org with tldp.org? Sure, it will be cool!
