### ISSUE TITLE
Unclear how issues in documents should be reported

### ISSUE THREAD

**Issue by Chealer** [tLDP/LDP#94]
Looking for a way to report issues in [the Advanced Bash-Scripting Guide](https://www.tldp.org/LDP/abs/html/intandnonint.html), I found no indication in the document. So I went looking for ways to report issues to the Linux Documentation Project.

Unfortunately, the Feedback link on LDP's website brings to [the _Linux Documentation Project Mailing Lists & Feedback_ page](https://www.tldp.org/mailinfo.html), which does not say a word about issue tracking.

Apologies for submitting this issue here - it does not look like the proper place to report it, but I could find no tracker other than this one.

**Comment by pbiering** [comment]
reporting issues via this way at least get some attention. If you find issues which you can correct directly via a fix in the source, then submit it by pull request. Otherwise open a ticket here and we try to fix or at least forward it to the maintainer.

**Comment by Chealer** [comment]
Thank @pbiering

**Comment by Chealer** [comment]
Why was this ticket closed?
